[versions]
androidLibraryVersion = "8.12.2"
androidXDocumentFileVersion = "1.1.0"
androidXExifinterfaceVersion = "1.4.1"
appCompatVersion = "1.7.1"
cameraCamera2Version = "1.4.2"
constraintlayoutVersion = "2.2.1"
coreKtxVersion = "1.17.0"
flexboxVersion = "3.0.0"
tensorflowLiteSupportVersion = "0.5.0"
coroutinesVersion = "1.10.2"
datastorePreferencesVersion = "1.1.7"
desugarVersion = "2.1.5"
espressoCoreVersion = "3.7.0"
gsonVersion = "2.13.1"
junit = "1.3.0"
junitJupiterApiVersion = "5.13.4"
junitPlatformRunnerVersion = "1.13.4"
junitVersion = "4.13.2"
kotlinAndroidVersion = "2.2.10"
kotlinCsvJvmVersion = "1.10.0"
androidXLifecycle = "2.9.3"
lunaVersion = "1.0.1"
materialVersion = "1.13.0"
markwonVersion = "4.6.2"
mockitoKotlinVersion = "6.0.0"
preferenceKtxVersion = "1.2.1"
printVersion = "1.1.0"
recyclerviewVersion = "1.4.0"
solVersion = "12.2.0"
workRuntimeKtxVersion = "2.10.3"
zxingVersion = "3.5.3"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompatVersion" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCamera2Version" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraCamera2Version" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraCamera2Version" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "androidXDocumentFileVersion" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferencesVersion" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
androidx-lifecycle-livedata-core-ktx = { module = "androidx.lifecycle:lifecycle-livedata-core-ktx", version.ref = "androidXLifecycle" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtxVersion" }
androidx-print = { module = "androidx.print:print", version.ref = "printVersion" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerviewVersion" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtxVersion" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "androidXExifinterfaceVersion" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarVersion" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexboxVersion" }
tensorflow-lite-support = { module = "org.tensorflow:tensorflow-lite-support", version.ref = "tensorflowLiteSupportVersion" }
markwon = { module = "io.noties.markwon:core", version.ref = "markwonVersion" }
markwon-linkify = { module = "io.noties.markwon:linkify", version.ref = "markwonVersion" }
markwon-image = { module = "io.noties.markwon:image", version.ref = "markwonVersion" }
markwon-simple = { module = "io.noties.markwon:simple-ext", version.ref = "markwonVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
junit = { module = "junit:junit", version.ref = "junitVersion" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiterApiVersion" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiterApiVersion" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitJupiterApiVersion" }
junit-platform-runner = { module = "org.junit.platform:junit-platform-runner", version.ref = "junitPlatformRunnerVersion" }
kotlin-csv-jvm = { module = "com.jsoizo:kotlin-csv-jvm", version.ref = "kotlinCsvJvmVersion" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutinesVersion" }
luna = { module = "com.kylecorry:luna", version.ref = "lunaVersion" }
material = { module = "com.google.android.material:material", version.ref = "materialVersion" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlinVersion" }
sol = { module = "com.kylecorry:sol", version.ref = "solVersion" }
zxing = { module = "com.google.zxing:core", version.ref = "zxingVersion" }

[plugins]
android-library = { id = "com.android.library", version.ref = "androidLibraryVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroidVersion" }